stages:
  - build
  - test
  - deploy

maven-build:
  image: maven
  stage: build
  script: "mvn clean package -B"
  artifacts:
    paths:
      - target/*.jar

maven-test:
  image: maven
  stage: test
  script: "mvn test"
  artifacts:
    paths:
      - target/*.jar

deploy-test:
  stage: deploy
  tags:
    - dalfcs_gitlab_docker_ci
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_TEST_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - develop

deploy-prod:
  stage: deploy
  tags:
    - dalfcs_gitlab_docker_ci
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_PROD_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - main



